const desertInfo = [
  { id: 1,
    name: "Dish 1",
    price: "R15.50",
    description: "Description of Dish 1",
  },
  { id: 2,
    name: "Dish 2",
    price: "R15.50",
    description: "Description of Dish 2",
  },
  { id: 3,
    name: "Dish 3",
    price: "R15.50",
    description: "Description of Dish 3",
  },
  { id: 4,
    name: "Dish 4",
    price: "R15.50",
    description: "Description of Dish 4",
  },
  { id: 5,
    name: "Dish 5",
    price: "R15.50",
    description: "Description of Dish 5",
  },
];
const startersInfo = [
  { id: 1,
    name: "Starter Dish 1",
    price: "R15.50",
    description: "Description of Starter Dish 1",
  },
  { id: 2,
    name: "Starter Dish 2",
    price: "R15.50",
    description: "Description of Starter Dish 2",
  },
  { id: 3,
    name: "Starter Dish 3",
    price: "R15.50",
    description: "Description of Starter Dish 3",
  },
  { id: 4,
    name: "Starter Dish 4",
    price: "R15.50",
    description: "Description of Starter Dish 4",
  },
  { id: 5,
    name: "Starter Dish 5",
    price: "R15.50",
    description: "Description of Starter Dish 5",
  },
]

const mainsInfo = [
  { id: 1,
    name: "Main Dish 1",
    price: "R15.50",
    description: "Description of Main Dish 1",
  },
  { id: 2,
    name: "Main Dish 2",
    price: "R15.50",
    description: "Description of Main Dish 2",
  },
  { id: 3,
    name: "Main Dish 3",
    price: "15.00",
    description: "Description of Main Dish 3",
  },
  { id: 4,
    name: "Main Dish 4",
    price: "R15.50",
    description: "Description of Main Dish 4",
  },
  { id: 5,
    name: "Main Dish 5",
    price: "R33.77",
    description: "Description of Main Dish 5",
  },
];
export { desertInfo, startersInfo, mainsInfo };